name: Deploy

on:
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          apk add ruby git openssh
          gem install mustache

      - name: Run build script
        run: sh ./build.sh

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to forked repo via SSH
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "github-actions[bot]"
          cd output
          git init
          git remote add origin git@github.com:Early-Us/BeCareful-Client.git
          git checkout -b main
          git add .
          git commit -m "${{ github.event.commits[0].message }}"
          git push -f origin main
